### ISSUE TITLE
Missing column information in parsed data

### ISSUE THREAD

**Issue by hs-apotell** [alainmarcel/Surelog#1120] opened 2020-05-19 07:13 UTC
UHDM::BaseClass provides access to File name and Line No. but the column number is not getting propagated to it from the parser.

Food for thought - Would it be worth (or at least an option to) carrying forward the actual token data i.e. the ANTLR primitive forward to allow access to other critical information for the purposes of linting. Being able to tie the model back to actual token can be useful.

**Comment by alaindargelas** [comment] 2021-04-01 08:39
#1165 provides persisted column info. It is not the solutions discussed above, but should permit many applications.

**Comment by alaindargelas** [comment] 2021-04-05 08:32
#1170 introduces all the necessary infra to save that data in UHDM.
The changelist only saves the module information. All other objects of interest have to have their endline and endcolumn added to UHDM from the internal AST.

**Comment by alaindargelas** [comment] 2021-04-11 23:49
Fixed by #1197

**Closed by alaindargelas** 2021-04-11 23:49 UTC

**Comment by hs-apotell** [comment] 2021-04-25 10:10
> The changelist only saves the module information. All other objects of interest have to have their endline and endcolumn added to UHDM from the internal AST.

@alaindargelas Quick follow up. I just pulled down the latest and looks like you already completed the pending work. Is there anything left on this task to do?

**Comment by alaindargelas** [comment] 2021-04-25 22:13
Nope, it's all done. The issue is closed.

**Comment by hs-apotell** [comment] 2021-04-26 04:35
Thanks!!
